# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Conveyor-Monitored
version:      0.10
version_from: lib/Thread/Conveyor/Monitored.pm
installdirs:  site
requires:
    Thread::Conveyor:              0.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
